# .graphclientrc.yml
sources:
  - name: super-accounts
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/subgraphs/id/AQcWbD2DFtVnSFBqGyMJfBKaGoHpx8r5fyTSixgstkQF
        operationHeaders:
          Authorization: "Bearer {env.SUBGRAPH_API_KEY}"   # runtime
documents:
  - ./src/graphql/get-user-badges.gql
  - ./src/graphql/get-first-100-users-level-3.gql