# .graphclientrc.yml
sources:
  - name: super-accounts
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/72352/super-accounts-staging/version/latest
documents:
  - ./src/graphql/get-user-badges.gql
  - ./src/graphql/get-first-100-users-level-3.gql