# .graphclientrc.yml
sources:
  - name: super-accounts
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/${SUBGRAPH_API_KEY}/subgraphs/id/A8Hs1ciwnqsdR8owyFZ77GM5PEXpQBqUTEUpNcnUS6xt
documents:
  - ./src/graphql/get-user-badges.gql
  - ./src/graphql/get-first-100-users-level-3.gql