query GetUserBadges($user: String!) {
  badges {
    badgeId
    uri
    perks {
      id
      tier
      isCompleted
      maxClaims
      amount
      totalClaims
    }
    badgeTiers(orderBy: tier, orderDirection: asc) {
      points
      tier
      uri
    }
  }
  accountBadges(where: { user: $user }) {
    perkClaims {
      perk {
        id
        badgeId
        tier
        token
        amount
        maxClaims
        totalClaims
        isCompleted
      }
    }
    points
    tier
    badge {
      badgeId
      uri
      perks {
        id
        tier
        isCompleted
        maxClaims
        amount
      }
      badgeTiers(orderBy: tier, orderDirection: asc) {
        points
        tier
        uri
        perk {
          id
          badgeId
          tier
          token
          amount
          maxClaims
          totalClaims
          isCompleted
        }
      }
    }
  }
}
